// Сваляне на генерирания проект като .zip директно от браузъра (JSZip) —
// работи и когато Node сървърът не е пуснат.
import JSZip from 'jszip';

const README = (projectName) => `# ${projectName || 'WebForge project'}

Generated by CHORUS WebForge.

## Run

### Static frontend
Open \`frontend/index.html\` in a browser, or serve the folder:
\`\`\`
npx serve frontend
\`\`\`

### With backend
\`\`\`
cd backend
npm install
npm start
\`\`\`
Then open http://localhost:3000
`;

export async function buildProjectZip(files = [], projectName = 'website') {
  const zip = new JSZip();
  for (const f of files) {
    if (!f?.path || typeof f.content !== 'string') continue;
    // само относителни пътища — никакви ../ изненади в архива
    const safe = f.path.replace(/\\/g, '/').replace(/^(\.\.\/)+/, '').replace(/^\/+/, '');
    if (!safe || safe.includes('../')) continue;
    zip.file(safe, f.content);
  }
  zip.file('README.md', README(projectName));
  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
}

export async function downloadProjectZip(files, projectName = 'website') {
  const blob = await buildProjectZip(files, projectName);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(projectName || 'website').replace(/[^a-z0-9-_]+/gi, '-').toLowerCase()}.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
